### PR TITLE
Fix shell scripts according to ShellCheck guidelines

### LINKED ISSUE #2835: Fix shell scripts according to ShellCheck's recommendations
Hi! Some of the scripts in `scripts` folder do not pass [ShellCheck](https://github.com/koalaman/shellcheck) analysis. For example:
```
$ shellcheck gdb_load_stm32.sh 

In gdb_load_stm32.sh line 3:
grep 'QSPI)' ./conf/lds.conf > /dev/null && echo "This script doesn't work with QSPI sections!" && exit -1
                                                                                                        ^-- SC2242 (error): Can only exit with status 0-255. Other data should be written to stdout/stderr.


In gdb_load_stm32.sh line 6:
GDB_CMD_FILE=$(mktemp --tmpdir=$PWD embox_gdb_stm32f7_qspi.XXXX)
                               ^--^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
GDB_CMD_FILE=$(mktemp --tmpdir="$PWD" embox_gdb_stm32f7_qspi.XXXX)


In gdb_load_stm32.sh line 8:
EMBOX_BIN=$(mktemp --tmpdir=$PWD embox_XXXX.bin)
^-------^ SC2034 (warning): EMBOX_BIN appears unused. Verify use (or export if used externally).
                            ^--^ SC2086 (info): Double quote to prevent globbing and word splitting.

…
```

I would like to make a contribution and I am willing to fix such issues for all shell scripts from said folder. Hence I wanted to ask if this kind of contribution will be of any value for the project?

### PR DESCRIPTION
**Pull request by wawuwo**
Hi! This PR resolves #2835 

The most part of the changes is trivial. It is quoting variables with double quotes to protect them from word splitting and globbing. This is especially important for variables containing paths (if a path in such a variable would accidentely contain spaces it would be splited into multiple substrings) and for many other variables too. Bash's word splitting can be very surprising even in obvious-looking commands: http://mywiki.wooledge.org/BashPitfalls#echo_.24foo.

Other changes are:
1. Handling of failed `cd`s, either by wrapping operation requiring `cd` in a subshell, or by explicit `|| exit 1`
2. Joining multiple 'echo string >> file' lines into a group command with a single redirect (https://www.shellcheck.net/wiki/SC2129)
3. Replacing indirect exit-code checks with direct ones, i.e. snippets like this
```
egrep '(vmx|svm)' /proc/cpuinfo > /dev/null
if [ $? -eq 0 ]; then
```
was rewritten like this
```
if grep -q -E '(vmx|svm)' /proc/cpuinfo; then
```
A nice benefit of this is that `grep`s `-q` short-circuits computation, terminating grep after first match.
4. Another changes, like style-related, etc. Most commit messages have a list of them.

Though PR name is «fix according to ShellCheck guidelines», changes introduced by it do not follow _all_ ShellCheck suggestions. I skipped SC suggestions if I wasn't sure that following it wouldn't change code's semantic. But if I followed them thinking that a change was safe, I might have been wrong and the change broke something.

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@wawuwo Thanks a lot.
I'll check it as soon as possible

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
Hi @wawuwoThanks a lot.
I've aproved this PR

It looks OK. However I couldn't check everything because there are too many changes in different parts. So can you split you PR on several PRs. I mean for example all commits which connect with  ./scqripts/qemu/auto_qemu.sh extract to a separate PR. You don't need to squash commits as I see, but reviewing so many changes is too hard for me :(

**Comment by wawuwo** [comment]
@anton-bondarev I completely understand, it is a lot of work to check all those commits (33 of them! argh!..) and yes, I can split them into multiple PRs!

I've cherry-picked commits affecting `scripts/qemu/auto_qemu` and anything related to it into a new branch and submitted a new PR (embox/pull/2857) from this branch. I do hope this will ease the job of checking them.

**Comment by anton-bondarev** [comment]
#2847
#2857
#2863
#2876

**Comment by wawuwo** [comment]
I think #2888 is the last PR in the series and this PR should be closed after merging it.

Of course there is still a room for improvement and for some scripts ShellCheck still suggests changes, but a lot of its warnings has been fixed and I believe the code has become a tiny bit better :)

**Comment by anton-bondarev** [comment]
> Of course there is still a room for improvement and for some scripts ShellCheck still suggests changes, but a lot of its warnings has been fixed and I believe the code has become a tiny bit better :)

Yes! Thank you very much!

> I think https://github.com/embox/embox/pull/2888 is the last PR in the series and this PR should be closed after merging it.

I think that it will berrt if I close this PR and the issue next week. I already ponted all related PRs.

**Comment by anton-bondarev** [comment]
@wawuwo Thanks a lot!
all changes from this PR have been merged with following PRs
#2847
#2857
#2863
#2876
#2878
#2879
#2880
#2882
#2884
#2885
#2887
#2888

**Pull request closed without merging**
