### PR TITLE
Add unit tests for strcpy() and strncpy()

### LINKED ISSUE #1851: Add unit tests for strcpy() & strncpy()
Implement some test cases for standard strcpy() & strncpy()

### PR DESCRIPTION
**Pull request by calenrobinette**
Closes #1851

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@calenrobinette Can you add some more tests?
For example checking for NULL arguments and checking for zero argument for length in strncmp()

**Comment by calenrobinette** [comment]
I think my 2nd test in strncpy has a length of zero. I'll add a test for `strncpy(dest, src, 0)` as well as for NULL for both.

**Comment by calenrobinette** [comment]
Added the additional unit tests. Let me know if they are what you were looking for.

**Comment by anton-bondarev** [comment]
@calenrobinette Please rebase your PR under embox/master
The only your commits have to be in your PR

**Comment by anton-bondarev** [comment]
@calenrobinette For rebasing you should do follow
```
git fetch upstream
git rebase -i upstream/master
```
Then you remove not your commits.
then
```
git push origin +1851-add-unit-tests-for-strcpy
```
Now there are not yours changes you can see it [https://github.com/embox/embox/pull/1898/files](https://github.com/embox/embox/pull/1898/files)

**Comment by anton-bondarev** [comment]
@calenrobinette For now You can just create a new PR with only your changes (tests and Mybuild)

**Pull request closed without merging**
