### PR TITLE
add math testsuite: copysign

### PR DESCRIPTION
**Pull request by diamant3**
this is my PR for #3446

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by diamant3** [comment]
Thank you, I'll take note of that!

**Comment by anton-bondarev** [comment]
@diamant3 Except this I found a problem on our CI
[https://github.com/embox/embox/actions/runs/11366386209/job/31616649368](https://github.com/embox/embox/actions/runs/11366386209/job/31616649368). I reproduced the error on my host.

have you checked it? I mean have you run x86/test/units on your host after adding your tests?
If not, please try to be more careful next time! :)

It seems the problem in a test
```
TEST_CASE("Test for copysign(NAN, -2.0)") {
	test_assert(copysign(NAN, -2.0) == -NAN);
}
```

**Comment by anton-bondarev** [comment]
Now I just disable this test #3457

**Pull request merged**
