### PR TITLE
mips: ralink: add ralink SoC interrupt controller

### PR DESCRIPTION
**Pull request by 123serge123**
I've added Ralink SoC interrupt controller support and build config to use it imstead of mips INTC.

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
@123serge123 Thank you very much!

I've approved it. Could you prepare to merge (rebase under embox master)?

We will be very grateful to you if you create a README file with a description how to run a 'rt5350' platform. Or may be a wiki page

**Comment by anton-bondarev** [comment]
> Something like:

Thanks a lot. This is what I want.

> So I do not understand what you mean.

This is just for the linearization of git history. But I think you are right it's not necessary for this time. So I've merge it as is

**Comment by anton-bondarev** [comment]
> Something like:

I created a wiki page for the instructions
[https://github.com/embox/embox/wiki/Platform-Ralink-rt5350](https://github.com/embox/embox/wiki/Platform-Ralink-rt5350)
Thanks a lot!

**Comment by 123serge123** [comment]
Oh! Sorry that patch from local repo for cmd/hardware/mem.c was included without additional comment.
But it's really useful for check of memory for debugging.

**Comment by anton-bondarev** [comment]
> But it's really useful for check of memory for debugging.

Yes, I think so.

**Pull request merged**
