### PR TITLE
Enable tish read from keyboard correctly (through linenoise)

### PR DESCRIPTION
**Pull request by KlyukinSA**
https://github.com/embox/embox/issues/2263

In original linenoise there is [nonblocking API](https://github.com/antirez/linenoise#asyncrhronous-api). In `embox/third-party/lib/linenoise` there is no such, so O_NONBLOCK disabling in linenoiseRawMode scope can be added to protect readline.

Now `x86/test/lang` works correctly

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@KlyukinSA Thanks a lot!

It's a possible way to solve the issue.

However I looked at original linenoise.c. there is no nonbloking API using in it. Maybe the problem is that when 'chibi-scheme' returns Embox won't restore termios flags?

**Comment by KlyukinSA** [comment]
@anton-bondarev 
> However I looked at original linenoise.c. there is no nonbloking API using in it. 

It is described here: https://github.com/antirez/linenoise#asyncrhronous-api. In https://github.com/antirez/linenoise/blob/master/linenoise.c there is linenoiseEditFeed() which is a part of API

**Comment by anton-bondarev** [comment]
@KlyukinSA Hi, can I close this PR. It seems it fixed in #2836

**Comment by KlyukinSA** [comment]
@anton-bondarev  hi yes sure

**Pull request closed without merging**
