### PR TITLE
Added unit-tests for cos() functions (math.h)

### PR DESCRIPTION
**Pull request by SurajSonawane2415**
#2964 I have resolved this issue. Please review this pull request.

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@SurajSonawane2415  Thanks!
Could you  also please add  your tests to the x86/test/units template?
You should do it with a new commit

**Comment by SurajSonawane2415** [comment]
> @SurajSonawane2415 Thanks! Could you also please add your tests to the x86/test/units template? You should do it with a new commit

Done!

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by SurajSonawane2415** [comment]
**Test run results on qemu:**
 
Screenshot from 2024-05-19 02-43-48

Screenshot from 2024-05-19 02-44-12

**Comment by anton-bondarev** [comment]
@SurajSonawane2415 thank you very much. I've already merged it. Sorry  sorry for not telling you.

**Comment by SurajSonawane2415** [comment]
Yes, I know it's merged. I sent it for more information, If a newcomer wants to work on any other good first issue, they will get information about testing.

**Comment by anton-bondarev** [comment]
> Yes, I know it's merged. I sent it for more information, If a newcomer wants to work on any other good first issue, they will get information about testing.

Yes, I see. Thanks a lot!

**Pull request merged**
