### PR TITLE
Third-party: BSP: Port Embox to Nucleo-l476rg

### LINKED ISSUE #2034: Port on NUCLEO-L476RG
Add supporting NUCLEO-L476RG board

### PR DESCRIPTION
**Pull request by puranjaymohan**
Add the BSP and template for the ST's Nucleo-l476rg Board.
This closes #2034
It builds correctly but I have to test it on the board.

Signed-off-by: Puranjay Mohan <puranjay12@gmail.com>

### CODE REVIEW

**Comment by puranjaymohan** [comment]
@anton-bondarev It has some errors which have to be resolved, somehow `stm32l476xx.h` is included whereas `stm32l475xx.h` should be included, also the errors are mostly due to redefinitions. I think I missed something or I forgot to change something somewhere please have a look and help me.
Thanks

**Comment by anton-bondarev** [comment]
@puranjaymohan Have you already tested that UART output is working?

**Comment by puranjaymohan** [comment]
> @puranjaymohan Have you already tested that UART output is working?

@anton-bondarev I tried testing it on the board but when when I did the `monitor reset` command, an error occurred.
```
Unable to match requested speed 500 kHz, using 480 kHz
```
You might have seen this earlier, how to correct this?

**Comment by anton-bondarev** [comment]
@puranjaymohan 

> ```
> Unable to match requested speed 500 kHz, using 480 kHz
> ```
> 
> 
> You might have seen this earlier, how to correct this?

No, I haven't met it early. But there are some similar problems in different forums
For example (https://www.openstm32.org/forumthread562)

How do you start 'openocd'?

**Comment by anton-bondarev** [comment]
@puranjaymohan Have you loaded any images into your board? If yes, how you've done one?

**Comment by anton-bondarev** [comment]
@puranjaymohan 
The output from 'openocd' from one of my available boards
```
sudo openocd -f /usr/share/openocd/scripts/board/st_nucleo_f4.cfg 
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
none separate
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Info : STLINK v2 JTAG v29 API v2 SWIM v18 VID 0x0483 PID 0x374B
Info : using stlink api v2
Info : Target voltage: 3.248180
Info : stm32f4x.cpu: hardware has 6 breakpoints, 4 watchpoints

```

**Comment by puranjaymohan** [comment]
> @puranjaymohan Have you loaded any images into your board? If yes, how you've done one?

I have used the following commands in GDB, after opening openocd in another terminal.
```
$ arm-none-eabi-gdb build/base/bin/embox
(gdb) target remote :3333
(gdb) monitor halt
(gdb) load
(gdb) monitor reset
(gdb) continue
```

but when I put the `monitor reset` command it gives that error.

**Comment by anton-bondarev** [comment]
> sudo openocd -f /usr/share/openocd/scripts/board/st_nucleo_l476rg.cfg

Right, what output?



> ```
> $ arm-none-eabi-gdb build/base/bin/embox
> (gdb) target remote :3333
> (gdb) monitor halt
> (gdb) load
> (gdb) monitor reset
> (gdb) continue
> ```
> 
> but when I put the `monitor reset` command it gives that error.

Try to use `monitor reset halt ` before 'load' in spite of any errors

**Comment by puranjaymohan** [comment]
Here are the outputs for the commands
```
sudo openocd -f /usr/share/openocd/scripts/board/st_nucleo_l476rg.cfg                                                         95%    10392
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 500 kHz
adapter_nsrst_delay: 100
none separate
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : Unable to match requested speed 500 kHz, using 480 kHz
Info : Unable to match requested speed 500 kHz, using 480 kHz
Info : clock speed 480 kHz
Info : STLINK v2 JTAG v34 API v2 SWIM v25 VID 0x0483 PID 0x374B
Info : using stlink api v2
Info : Target voltage: 3.255010
Info : stm32l4x.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : accepting 'gdb' connection on tcp/3333
Info : device id = 0x10076415
Info : flash size = 1024kbytes
undefined debug reason 7 - target needs reset
Info : Unable to match requested speed 500 kHz, using 480 kHz
Info : Unable to match requested speed 500 kHz, using 480 kHz
adapter speed: 480 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0801160a msp: 0x20002c80
Info : Unable to match requested speed 500 kHz, using 480 kHz
Info : Unable to match requested speed 500 kHz, using 480 kHz
adapter speed: 480 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0801160a msp: 0x20002c80
adapter speed: 4000 kHz
Info : Padding image section 0 with 2 bytes
Info : Padding image section 1 with 16 bytes
target halted due to breakpoint, current mode: Thread 
xPSR: 0x61000000 pc: 0x20000050 msp: 0x20002c80
Warn : block write succeeded
Warn : keep_alive() was not invoked in the 1000ms timelimit. GDB alive packet not sent! (2508). Workaround: increase "set remotetimeout" in GDB
Info : Unable to match requested speed 500 kHz, using 480 kHz
Info : Unable to match requested speed 500 kHz, using 480 kHz
adapter speed: 480 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0801160a msp: 0x20002c80
Info : Unable to match requested speed 500 kHz, using 480 kHz
Info : Unable to match requested speed 500 kHz, using 480 kHz
adapter speed: 480 kHz
Warn : WARNING! The target is already running. All changes GDB did to registers will be discarded! Waiting for target to halt.
```

and from GDB

```
(gdb) target remote :3333
Remote debugging using :3333
0x00000000 in ?? ()
(gdb) monitor reset halt
Unable to match requested speed 500 kHz, using 480 kHz
Unable to match requested speed 500 kHz, using 480 kHz
adapter speed: 480 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0801160a msp: 0x20002c80
(gdb) load
Loading section .text, size 0x20b06 lma 0x8000000
Loading section .ARM.exidx, size 0x8 lma 0x8020b08
Loading section .rodata, size 0x13f40 lma 0x8020b20
Loading section .data, size 0x4d8 lma 0x8034a60
Start address 0x0801160a, load size 216870
Transfer rate: 41 KB/sec, 12757 bytes/write.
(gdb) monitor reset
Unable to match requested speed 500 kHz, using 480 kHz
Unable to match requested speed 500 kHz, using 480 kHz
adapter speed: 480 kHz
(gdb) continue 
Continuing.
WARNING! The target is already running. All changes GDB did to registers will be discarded! Waiting for target to halt.

```

**Comment by anton-bondarev** [comment]
@puranjaymohan It looks rather normal
But you should use `target extended-remote :3333` instead of `target remote :3333`  as desribed [here](https://sourceforge.net/p/openocd/mailman/message/34077647/) 

Can you set any breakpoints? for example 'b kernel_start' and what happens if you break execution (ctlr + 'c')

**Comment by puranjaymohan** [comment]
@anton-bondarev I don't this the problem is due to openocd. I took the embox.bin to my windows os and flashed the board using ST's st-link utility, there it flashed properly but when I turned on the Serial monitor and reset the board using the button, nothing was printed. This issue has to be debugged. I am trying.

**Comment by puranjaymohan** [comment]
Also, these both work as you said, I feel this problem is due to the code or the tempelate.
Stopping execution

```
(gdb) continue 
Continuing.
^C
Program received signal SIGINT, Interrupt.
arch_shutdown (mode=ARCH_SHUTDOWN_MODE_ABORT) at third-party/bsp/stml4cube/nucleo_l476rg/arch.c:91
91		while(1) {
```

and breakpoints

```
(gdb) monitor reset halt
Unable to match requested speed 500 kHz, using 480 kHz
Unable to match requested speed 500 kHz, using 480 kHz
adapter speed: 480 kHz
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0801160a msp: 0x20002c80
(gdb) b kernel_start 
Breakpoint 1 at 0x80001c6: file src/kernel/init.c, line 25.
(gdb) c
Continuing.
Note: automatically using hardware breakpoints for read-only addresses.

Breakpoint 1, kernel_start () at src/kernel/init.c:25
25		kernel_init();

```

**Comment by anton-bondarev** [comment]
@puranjaymohan 
Yes, I'm sure that the problem not in gdb or openocd. I just wanted to make sure that you can debug on the board. Now your program works well and I think the problem only in UART output. I think the problem maybe not only in template. I seem that the problem can be in uart settings or  arch_init  Could you load any example from Cubel4 for your board (hello world will be enough) and check uart settings in Embox. I mean compare pin settings in HAL_UART_MspInit (Embox and Example). Also it should  be checked SystemClock_Config routine. It has to be similar as the example.

**Comment by puranjaymohan** [comment]
@anton-bondarev I tried to check the base address of the UART2 peripheral if it is right.
As you can see the base address is 0x40004400 which is correct according to memory map, also I checked baud rate is correct.

```
(gdb) b HAL_UART_MspInit 
Breakpoint 1 at 0x800275a: HAL_UART_MspInit. (2 locations)
(gdb) c
Continuing.
Note: automatically using hardware breakpoints for read-only addresses.

Breakpoint 1, HAL_UART_MspInit (huart=0x20002ba0) at src/drivers/serial/stm32_usart/hal_msp_l4.c:87
87		void *uart_base = huart->Instance;
(gdb) huart
Undefined command: "huart".  Try "help".
(gdb) s
91		USART_TX_GPIO_CLK_ENABLE(uart_base);
(gdb) p uart_base 
$1 = (void *) 0x40004400

```

**Comment by anton-bondarev** [comment]
>  I tried to check the base address of the UART2 peripheral if it is right.
> As you can see the base address is 0x40004400 which is correct according to memory map, also I checked baud rate is correct.

@puranjaymohan Great!
There are two HAL_GPIO_Init in HAL_UART_MspInit could you check arguments for both?

**Comment by puranjaymohan** [comment]
@anton-bondarev It works :smile: I found the error, it was due to some if-else statements in hal_msp_l4 file, you can see more in my latest commit, after doing all these changes it finally works and I can see embox in the serial monitor. It gives me immense joy to be able to help in porting Embox to a new board. Looking forward to my new challenge.

**Comment by anton-bondarev** [comment]
@puranjaymohan Thank you very much!

I've merged it! :)

**Pull request merged**
