### PR TITLE
Added unit tests for strrchr and strchrnul

### LINKED ISSUE #1854: Add unit tests for strrchr() & strchrnul()
There are some test case for strchr(). Implement also unit tests for strchrnul() and strrchr()

### PR DESCRIPTION
**Pull request by vladtp**
Fixes #1854

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@vladtp Thanks
Please rebase and squash commits. There would be 2 commits (tests and template modification)

**Comment by vladtp** [comment]
@anton-bondarev sure, will do that, but I am still a beginner on git. Can I rebase and squash this PR, or do I need to do that first and then create another PR?

**Comment by anton-bondarev** [comment]
> @anton-bondarev sure, will do that, but I am still a beginner on git. Can I rebase and squash this PR, or do I need to do that first and then create another PR?

@vladtp There will be 2 commits in this PR. For that you should rebase and squash commits. Now also it's necessary to solve some conflicts. Let's try to do that:

```
git fetch upstream
git rebase -i upstream/master
```
after that you will be able to squash commits (you can change commit history during interactive (-i) rebasing
After you squash two your commits
you'll get messages about conflicts. resolve it and commit changes.
After that you have to force push you branche
```
git push origin +unit-tests-strrchr-strchrnul
```

**Comment by vladtp** [comment]
@anton-bondarev done

**Pull request merged**
