### PR TITLE
Add duktape

### PR DESCRIPTION
**Pull request by sikmir**
> Duktape is an embeddable Javascript engine, with a focus on portability and compact footprint.
https://github.com/svaarala/duktape

Build steps:
1. `make confload-arm/qemu`
2. Add `include third_party.cmd.duktape` to `conf/mods.config`
3. `make`

*NOTE*: `strptime` and `cbrt` are not implemented.

Run steps:
```
root@embox:/#duk ./fib.js                                                       


  ______
 |  ____|                                            __          __
 | |___  _ __ ___            ____  ____  ____  _____/ /   _____ / /
 |  ___|| '_ ` _ \          / __ \/ __ \/ __ \/ ___/ /   |_____| |
 | |____| | | | | |_ _ _   / /_/ / /_/ / /_/ (__  )_/    |_____| |
 |______|_| |_| |_(_|_|_)  \____/\____/ .___/____(_)           | |
                                     /_/                        \_\
 ASSERTION FAILED on CPU 0
	at src/kernel/irq.c:168
	in function irq_dispatch

__next_at_line_168
Data abort exception!
regs:
00090078 09e0aa04 e59ff018 fffffff8
001b8004 00000000 00000000 00000000
00000000 00000000 00000000 09e0aa04
09e0a9e0 00002e3c
```

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@sikmir 
It seems the problem is in math lib
I changed
```
	include embox.compat.libc.math_openlibm
	//include embox.compat.libc.math_builtins
```
and it works
```
root@embox:/#duk fib.js
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181
root@embox:/#
```
I think we should remove `include third_party.cmd.duktape` from `arm/qemu` and add it to `x86/test/lang` template

**Review by anton-bondarev — APPROVED** [review]
LGTM
I've checked it on `arm/qemu` and `x86/qemu` with `openlibm` instead of `math_builtin` implementation library

**Comment by sikmir** [comment]
> I think we should remove `include third_party.cmd.duktape` from `arm/qemu` and add it to `x86/test/lang` template

Moved.

**Comment by anton-bondarev** [comment]
@sikmir Thanks a lot!
Now Embox has JS support!

**Pull request merged**
