### PR TITLE
Coap integration

### PR DESCRIPTION
**Pull request by PhilippDolgolev**
Сбилдили библиотеку и ничего не сломали :+1:

### CODE REVIEW

**Comment by AntonKozlov** [comment]
Great! How could I check the library works?

**Comment by anton-bondarev** [comment]
Thanks!
Can you also build examples (client & coat-server) from coap-lib?
You should make it as separate modules and than you can start two Embox instances, one with client other with server and show communication through libcoap.

**Comment by PhilippDolgolev** [comment]
@AntonKozlov , @anton-bondarev when we tried to build coap-server, we found trouble

```
../libcoap.a(net.o): In function `coap_malloc_node':
/home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/net.c:54: undefined reference to `rpl_malloc'
../libcoap.a(net.o): In function `coap_new_context':
/home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/net.c:299: undefined reference to `rpl_malloc'
../libcoap.a(resource.o): In function `coap_resource_init':
/home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/resource.c:311: undefined reference to `rpl_malloc'
../libcoap.a(resource.o): In function `coap_add_attr':
/home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/resource.c:351: undefined reference to `rpl_malloc'
../libcoap.a(resource.o): In function `coap_add_resource':
/home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/resource.c:445: undefined reference to `rpl_malloc'
../libcoap.a(resource.o):/home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/resource.c:445: more undefined references to `rpl_malloc' follow
collect2: error: ld returned 1 exit status
make[7]: *** [coap-server] Error 1
```

What we should do with rpl_malloc?
Also in logs we found some failed checks(on ubuntu 14.04/16.04 they are ok):

```
checking for i386-unknown-none-ranlib... no
checking sys/unistd.h usability... no
checking sys/unistd.h presence... no
checking for sys/unistd.h... no
checking syslog.h usability... no
checking syslog.h presence... no
checking for syslog.h... no
checking for GNU libc compatible malloc... no
```

I assume that trouble in specific flags for compiler, can you give advice about them?

**Comment by anton-bondarev** [comment]
Please, push your Mybuild file, I think that your trouble in it.
 Try to use ` @Build(stage=2, script="$(EXTERNAL_MAKE)")` instead of stage=1 for building application and stage=1 for libcoap. Except this you should use ` @BuildDepends ` for applications

**Comment by PhilippDolgolev** [comment]
@anton-bondarev Examples from libcoap builded just after building libcoap. It is rule in their makefile, and it is not obviously how elegantly split examples from building lib(I see only one way, copy examples to embox and write our specific makefile).
Also I tried apply  ```@Build(stage=2, script="$(EXTERNAL_MAKE)")```, but all troubles appeared again. I assume that we should fix this troubles first of all.

**Comment by AnastasiaSulyagina** [comment]
I think the main problem is here
`
checking for GNU libc compatible malloc... no
`
Maybe if it's true you could advice us how to reference embox's malloc from the example?

**Comment by anton-bondarev** [comment]
@AnastasiaSulyagina You are right, but what the reason of this situation.
When you build external applications Embox have to create a link to internal compiler (with own libraries path). Today I'll investigate your problem.

**Comment by anton-bondarev** [comment]
@PhilippDolgolev @AnastasiaSulyagina Look at [Makefile in third-party/iperf](https://github.com/embox/embox/blob/master/third-party/iperf/Makefile). There is a definition `-Drpl_malloc=malloc` in it. May be it resolve the problem

**Comment by AnastasiaSulyagina** [comment]
It does not break with the command. Thanks

**Comment by AnastasiaSulyagina** [comment]
Tried to add examples as console apps, got an error. When adding Mybuild looked at nano behavior(nano can be called from embox terminal). While executing same commands nano builds but our examples fail. Could you please explain what is the problem?
```
External build complete
mk/image2.mk:109: warning: undefined variable `BUILD_DEPS_CPPFLAGS'
mk/image2.mk:109: warning: undefined variable `BUILD_DEPS_LDFLAGS'
mk/image2.mk:109: warning: undefined variable `BUILD_DEPS_CPPFLAGS'
mk/image2.mk:109: warning: undefined variable `BUILD_DEPS_LDFLAGS'
ld -r -o build/base/obj/module/third_party/lib/coap_server.o.build.o -N -g -m elf_i386 \
		./build/base/obj/../../extbld/third_party/lib/coap_server/install/server.o
ld: Relocatable linking with relocations from format elf64-x86-64 (./build/base/obj/../../extbld/third_party/lib/coap_server/install/server.o) to format elf32-i386 (build/base/obj/module/third_party/lib/coap_server.o.build.o) is not supported
make[4]: *** [build/base/obj/module/third_party/lib/coap_server.o] Error 1
make[3]: *** [build] Error 2
make[2]: *** [build] Error 2
make[1]: *** [build] Error 2
make: *** [all] Error 2
```

**Comment by anton-bondarev** [comment]
@AnastasiaSulyagina Have you `--target`  in you ./configure line as 'nano' Makefile `--target=$(AUTOCONF_TARGET_TRIPLET)`?

**Comment by AnastasiaSulyagina** [comment]
We had `--host=$(AUTOCONF_TARGET_TRIPLET)`. Added target but got the same error.

**Comment by AntonKozlov** [comment]
You've tried examples from that are in this PR?
They have custom and simple Makefile supplied.

**Comment by AntonKozlov** [comment]
Sorry, sent comment above too early, updated

**Comment by AnastasiaSulyagina** [comment]
Yes, current state is committed. Fails on make.
Will update when try flags

**Comment by anton-bondarev** [comment]
@AnastasiaSulyagina Sorry I didn't notice your last commit!
Now I understand your mistake. You've just copied sources file server.c and client.c and also you used original Makefile for it, But you had to build these applications by Embox build system,
You should create Mybuild file with two modules (Embox applications) see [cat command](https://github.com/embox/embox/blob/master/src/cmds/fs/Cat.my) for example. You also should use @BuildDepends annotation.
If you do so your application will be build with the same flags that all others modules, as said @AntonKozlov

**Comment by PhilippDolgolev** [comment]
@anton-bondarev This files added to commit by mistake, but they are not involved in build. We will delete this files. Examples builded together with lib, and have same  [Mybuild](https://github.com/ShitCommit1/embox/blob/8bcb3f9dd18ecbe5bbddbcbe486b39096555287c/third-party/libcoap/lib/Mybuild) file.

I think that advice from @AntonKozlov will help us.

**Comment by AnastasiaSulyagina** [comment]
Fails again with -m32
```
make[7]: Entering directory `/home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/examples'
cc -g -Wall -m32 -I.. -Drpl_malloc=malloc -DWITH_POSIX  -c -o server.o server.c
cc -o coap-server server.o -L.. -lcoap 
/usr/bin/ld: skipping incompatible ../libcoap.a when searching for -lcoap
/usr/bin/ld: cannot find -lcoap
collect2: error: ld returned 1 exit status
make[7]: *** [coap-server] Error 1
make[7]: Leaving directory `/home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/examples'
touch /home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/.builded
cp /home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/libcoap.a /home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/install/
cp /home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/*.h /home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/install/
cp /home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/examples/server.o /home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/install/../../coap_server/install/
cp /home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/examples/client.o /home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/install/../../coap_client/install/
cp: cannot stat ‘/home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/libcoap-4.1.1/examples/client.o’: No such file or directory
make[5]: *** [/home/parallels/Documents/embox/build/extbld/third_party/lib/libcoap/.installed] Error 1
make[4]: *** [build/base/gen/third_party/lib/libcoap.__extbld-target] Error 2
make[3]: *** [build] Error 2
make[2]: *** [build] Error 2
make[1]: *** [build] Error 2
make: *** [all] Error 2

```

**Comment by AntonKozlov** [comment]
Looking at build log of coap itself
```
cc -Wall -Wextra -std=c99 -pedantic -g -O2 -Drpl_malloc=malloc -DWITH_POSIX  -c -o pdu.o pdu.c
...
```
it's easy to say that configure haven't done it's job and lost CC variable passed. I've tried to pass it to make too and some result:
```
  cd $(PKG_SOURCE_DIR) && ( \
                make \
                        CC=$(EMBOX_GCC) \
        )
```

```
/embox/mk/extbld/arch-embox-gcc -g -Wall -g -O2 -I.. -Drpl_malloc=malloc -DWITH_POSIX  -c -o client.o client.c
...
client.c:511:51: error: 'IPV6_JOIN_GROUP' undeclared (first use in this function)
   result = setsockopt( ctx->sockfd, IPPROTO_IPV6, IPV6_JOIN_GROUP,
```

**Comment by Deryugin** [comment]
This configure script doesn't use `$LDFLAGS` as well, no matter if you use `export CC=...` or pass it as an argument. I'm pretty sure this is true for all the variables.

I can link `coap-server` by hand with `-m32` flag passed. Not sure if this is necessary when `$CC` is correct.

The configure script is pretty complex, so I have no idea how to fix it :(

**Comment by PhilippDolgolev** [comment]
@AntonKozlov I found usage of ```IPV6_JOIN_GROUP``` in  [./third-party/tcl/tcludp/tcludp_embox_compat.h](https://github.com/embox/embox/blob/master/third-party/tcl/tcludp/tcludp_embox_compat.h). And it's add via CPP in [Makefile](https://github.com/embox/embox/blob/master/third-party/tcl/tcludp/Makefile). Am I on right way?

**Comment by AntonKozlov** [comment]
Not really. tcludp is another third-party library, just as coap. It turns out that coap uses ipv6, and embox have preliminary ipv6 support, for example that define not presents.

There are some further actions: modify libcoap to use ipv4 instead of ipv6. You can make changes in build/extbld/third_party/lib/libcoap/libcoap-4.1.1 , they will not be overwritten on incremental `make`, but will not survive `make clean` or deletion of whole build/extbld/third_party/lib/libcoap/. Once you have a milestone, you could create a patch that will be applied to libcoap on clean build. You should diff your modified libcoap and vanilla libcoap, place a patch in third-party/libcoap/lib and add your patch in PKG_PATCHES, like in tcludp.

Second way is to provide some defines as tcludp do, by creating new local header file with stub definitions and files and add -include that_file.h in cpp flags (tcludp is an example for this too). 

In second way you could just disable client build. Or modify client to build. In second you'll be able to provide just stubs, they are usefull to get compiled, but be prepared that it will be not fully operate.

**Comment by AnastasiaSulyagina** [comment]
at least it builds

**Comment by AnastasiaSulyagina** [comment]
But when trying to run coap-server get
```
root@embox:/#coap_server
Jan 01 00:00:11 EMRG coap_new_context: socket
no context available for interface '::'
coap_server: Command returned with code -1: Unknown error code. PLEASE REPORT ISSUE 519!
tish error: #255

```
for client:
```
root@embox:/#coap_client -m get coap://[::1]/
getaddrinfo: service not supported for socket type
Jan 01 00:02:24 EMRG cannot create context
coap_client: Command returned with code -1: Unknown error code. PLEASE REPORT ISSUE 519!
tish error: #255
```

**Comment by PhilippDolgolev** [comment]
@AntonKozlov , @AnastasiaSulyagina Also we need understand this definitions:
```
#define IN_CLASSD(i) (((long)(i) & 0xf0000000) == 0xe0000000)
#define IN_MULTICAST(i) IN_CLASSD(i)
```

This definitions was taken from [netinet/in.h](http://www.mit.edu/afs.new/athena/astaff/reference/4.3network/sys/netinet/in.h), but in context of embox can be different.

**Comment by anton-bondarev** [comment]
@PhilippDolgolev 
```
#define IN_CLASSD(i) (((long)(i) & 0xf0000000) == 0xe0000000)
#define IN_MULTICAST(i) IN_CLASSD(i)
```
There are some types of IP addresses. One of them is [multicast address](https://en.wikipedia.org/wiki/Multicast_address) its mask is `224.0.0.0` or  `0xe0000000`

**Comment by anton-bondarev** [comment]
@AnastasiaSulyagina You have a problem with ipv6 sockets. Now I'm researching how you can overcome them

**Comment by anton-bondarev** [comment]
@AnastasiaSulyagina @PhilippDolgolev You can start coap_server in IPv4 interface by comand

> coap_server -A 0.0.0.0

**Comment by AnastasiaSulyagina** [comment]
Thanks! But there are still some troubles with client. Will try to research further

**Comment by AnastasiaSulyagina** [comment]
Seems that problem is the same, tried different flags - nothing worked.

**Comment by anton-bondarev** [comment]
@AnastasiaSulyagina I received follow output

```
root@embox:/#coap_server -A 0.0.0.0 & 
root@embox:/#coap_client -m get coap://127.0.0.1:5683
v:1 t:0 tkl:0 c:1 id:44402
This is a test server made with libcoap (see http://libcoap.sf.net)
Copyright (C) 2010--2013 Olaf Bergmann <bergmann@tzi.org>


root@embox:/#
```
but I modificated getaddrinfo() routine. I'm trying fix it today and you'll can pull my changes into your branch.

**Comment by anton-bondarev** [comment]
@PhilippDolgolev @AnastasiaSulyagina I fix getaddrinfo() Please update you branch and check libcoap work
`git remote add upstream https://github.com/embox/embox.git
git fetch upstream
git rebase origin/master
git push --force origin/coap-integration/`
And also remove redundant commits if not difficult

**Comment by PhilippDolgolev** [comment]
Seems it works.

**Comment by AntonKozlov** [comment]
Rebase was required, merged in as #970. Thank you!

**Pull request closed without merging**
