### PR TITLE
Lua53

### PR DESCRIPTION
**Pull request by sikmir**
*luabitop* no more useful since Lua 5.3 supports bitwise operators.
*LUA_USE_POSIX* requires follow ones:
```c
void _longjmp(jmp_buf env, int val);
int _setjmp(jmp_buf env);
int fflush(FILE *stream);
FILE *popen(const char *command, const char *mode);
int pclose(FILE *stream);
int getc_unlocked(FILE *stream);
void flockfile(FILE *file);
void funlockfile(FILE *file);
```
But lack of support in Embox, fix it workaround available.

### CODE REVIEW

**Comment by AntonKozlov** [comment]
In general, I support this merge.
But luasocket have some problems
```
./build/base/obj/embox-2.o: In function `mime_global_eol':
/var/lib/buildbot/slaves/embox/x86_test_lang/build/build/extbld/third_party/lib/luasocket/luasocket-d80bb0d82ba105c8fdb27e6174c267965d06ffb0/src/mime.c:664: undefined reference to `luaL_checkint'
./build/base/obj/embox-2.o: In function `global_skip':
/var/lib/buildbot/slaves/embox/x86_test_lang/build/build/extbld/third_party/lib/luasocket/luasocket-d80bb0d82ba105c8fdb27e6174c267965d06ffb0/src/luasocket.c:67: undefined reference to `luaL_checkint'
make[4]: *** [build/base/obj/image_nosymbols.o] Error 1
```

**Comment by abusalimov** [comment]
What do we do now? Revert this?

**Comment by sikmir** [comment]
I think no need to revert, I'll fix it asap. But.. up to you, no matter.

**Comment by abusalimov** [comment]
OK. BTW, I've added few templates to Travis builds recently (#732), so you will be able to follow the status after merging master into this branch!

**Pull request merged**
