### PR TITLE
Add copysign testsuite

### PR DESCRIPTION
**Pull request by diamant3**
for embox/embox#3446

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
Hi @diamant3 ,
Thanks!
I've approved it. Could you prepare to merge (rebase under upsteram/master) ?

**Comment by anton-bondarev** [comment]
@diamant3 I mean you should do following ([https://github.com/embox/embox/wiki/Contributing%3A-Git-workflow](https://github.com/embox/embox/wiki/Contributing%3A-Git-workflow))
add embox as upstream
`git remote add upstream https://github.com/embox/embox.git`
Update upstream information
`git fetch upstream`
Rebase under embox/master
`git rebase upstream/master`
Force push to your repo (update the PR)
'git push origin +copysign-test`

**Comment by diamant3** [comment]
Thank you! Sorry I will close this one and make a new PR here: #3456

**Comment by anton-bondarev** [comment]
> Thank you! Sorry I will close this one and make a new PR here: #3456

No problem. But it's really useful instruction for many projects :)

**Pull request closed without merging**
