### PR TITLE
1769 sp804 driver

### PR DESCRIPTION
**Pull request by EugenySvirin**

### CODE REVIEW

**Comment by alexkalmuk** [comment]
Thank you, but this driver is broken at the moment.

```cpp
/home/alexander/git/embox/src/drivers/clock/sp804_timer/sp804_timer.c:46:24: error: passing argument 1 of 'clock_tick_handler' makes pointer from integer without a cast [-Werror=int-conversion]
   46 |     clock_tick_handler(irq_nr, data);
```
and other compilation errors.

You can check with vexpress-a9 as it specified in the issue https://github.com/embox/embox/issues/1769:

* `make confload-arm/vexpress-a9`
* Edit `conf/mods.conf` and include `@Runlevel(0) include embox.driver.clock.sp804` there:
It's a part of mine mods.conf:
```
    @Runlevel(0) include embox.driver.clock.cortexa9(periph_base_addr=0x1e000000,irq_num=29)
    @Runlevel(0) include embox.driver.clock.sp804
    include embox.kernel.time.jiffies(cs_name="cortexa9_timer")
```
* `make`

**Comment by alexkalmuk** [comment]
You can take a look at the `src/drivers/clock/cortexa9_timer/` already used in this configuration to see how to fix sp804 correspondingly. It looks like signatures of some functions were changed, also now we such a declaration of the system timer:

```
CLOCK_SOURCE_DEF(cortexa9_timer, cortexa9_timer_init, NULL,
    &cortexa9_timer_event, &cortexa9_timer_counter);
```

sp804 lacks this definition.

**Comment by EugenySvirin** [comment]
Thank you, I will give it a try.

**Comment by EugenySvirin** [comment]
Reworked to fit new interface.
Seems to run ok on confload-arm/vexpress-a9, with mods changing: 

>        @Runlevel(0) include embox.driver.clock.cortexa9(periph_base_addr=0x1e000000,irq_num=29)
>        include embox.kernel.time.jiffies(cs_name="cortexa9_timer")
to       

>         @Runlevel(0) include embox.driver.clock.sp804
> 	include embox.kernel.time.jiffies(cs_name="sp804_timer")

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
@EugenySvirin I've approved the PR.
Please rebase upon embox/master and squash commits if it's necessary

**Pull request merged**
