### PR TITLE
Update stm32cubef7 up to v1.16.0

### PR DESCRIPTION
**Pull request by alexkalmuk**
Fixes https://github.com/embox/embox/issues/2037

Verified templates:

* arm/stm32f746g-discovery (telnet works)
* arm/stm32f769i-discovery
* project/pjsip/stm32f746g-discovery - works, but falls in asserts sometimes (I think more often than it was on previos version, but may be it's just randomness)
* project/pjsip/stm32f769i-discovery
* project/nuklear/stm32f746g-discovery
* project/qt4/stm32f746g_discovery
* platform/opencv/stm32f769i-discovery

SD card API was changed in this Cube, so we should test SD cards as well.

### CODE REVIEW

**Comment by alexkalmuk** [comment]
opencv tempaltes `platform/opencv/stm32f769i-discovery` is broken:

```
arm-none-eabi-ld: /home/alexander/git/embox/build/base/obj/image_nosymbols.o section `.rodata' will not fit in region `ROM'
arm-none-eabi-ld: region `ROM' overflowed by 155644 bytes
```

**Comment by alexkalmuk** [comment]
> opencv template `platform/opencv/stm32f769i-discovery` is broken:
> 
> ```
> arm-none-eabi-ld: /home/alexander/git/embox/build/base/obj/image_nosymbols.o section `.rodata' will not fit in region `ROM'
> arm-none-eabi-ld: region `ROM' overflowed by 155644 bytes
> ```

Hmm, it seems it's broken in master too.

**Comment by alexkalmuk** [comment]
> opencv template `platform/opencv/stm32f769i-discovery` is broken:
> 
> ```
> arm-none-eabi-ld: /home/alexander/git/embox/build/base/obj/image_nosymbols.o section `.rodata' will not fit in region `ROM'
> arm-none-eabi-ld: region `ROM' overflowed by 155644 bytes
> ```

Fixed in https://github.com/embox/embox/pull/2207

**Review by anton-bondarev — APPROVED** [review]
LGTM
I've checked pjsip & opencv on stm32f769i-discovery

**Pull request merged**
