### PR TITLE
compat: minor: Add tests for sinh() from math.h

### PR DESCRIPTION
**Pull request by sycamoremoon**
Modify the lib `math_simple` to `math_openlibm` in conf/mods.conf to make compiling correct

Resolve: #2991
See also: #2992, #2960

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
@sycamoremoon thanks for your contribution!

It's OK. 
Please could you also add your tests into x86/test/units temlate with a separate commit?
Then please rebase your branch under embox/master

**Comment by sycamoremoon** [comment]
No problem. May I ask whether reserve the last commit history and make a new commit or overlap the last commit history with rebase?
---- Replied Message ----
From Anton ***@***.***> Date 05/02/2024 16:47 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [embox/embox] compat: minor: Add tests for sinh() from math.h (PR #3245) 
@sycamoremoon thanks for your contribution!
It's OK.
Please could you also add your tests into x86/test/units temlate with a separate commit?
Then please rebase your branch under embox/master

**Comment by sycamoremoon** [comment]
This is my first PR and I'm happy for it .Thank you very much for your patient teaching

**Pull request merged**
