### PR TITLE
Added unit-tests for cosh() functions (math.h) 

### PR DESCRIPTION
**Pull request by perminder-17**
Fixes issue : #3270 

This pull request adds unit tests for cosh() function.

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
@perminder-17 Thanks!
I've approved it. Please prepare the PR to merge (rebase under upstream/master)

Small comment for the future. It's better to use a separate commit for templates modifications

**Comment by anton-bondarev** [comment]
@perminder-17 Do you have any problem with rebasing?

I see there are 2 conflicts

you should do the following
to rebase
`git fetch upstream`
`git rebase -i upstream/master`

you will get some conflicts to solve you have to modify conflicted files and then add it 
`git add src/compat/libc/math/tests/Mybuild`
`git add templates/x86/test/units/mods.conf`

And then you have to continue rebasing
`git rebase --continue`

**Comment by perminder-17** [comment]
> @perminder-17 Do you have any problem with rebasing?
> 
> I see there are 2 conflicts
> 
> you should do the following to rebase `git fetch upstream` `git rebase -i upstream/master`
> 
> you will get some conflicts to solve you have to modify conflicted files and then add it `git add src/compat/libc/math/tests/Mybuild` `git add templates/x86/test/units/mods.conf`
> 
> And then you have to continue rebasing `git rebase --continue`

Oops....Thanks so much. I wasn't having any problem with it. I was actually busy with my GSoC'24 work. Will do it today. Thanks:)

**Comment by anton-bondarev** [comment]
> > @perminder-17 Do you have any problem with rebasing?
> > I see there are 2 conflicts
> > you should do the following to rebase `git fetch upstream` `git rebase -i upstream/master`
> > you will get some conflicts to solve you have to modify conflicted files and then add it `git add src/compat/libc/math/tests/Mybuild` `git add templates/x86/test/units/mods.conf`
> > And then you have to continue rebasing `git rebase --continue`
> 
> Oops....Thanks so much. I wasn't having any problem with it. I was actually busy with my GSoC'24 work. Will do it today. Thanks:)

No problem!
Good luck with GSoC!

**Comment by perminder-17** [comment]
> Good luck with GSoC!

Thankyou so much @anton-bondarev . 
Let me know if that's looking good to you?

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
> > Good luck with GSoC!
> 
> Thankyou so much @anton-bondarev . Let me know if that's looking good to you?

Yes. Thanks. It's ok now

**Pull request merged**
