### PR TITLE
Bcm spi dma

### PR DESCRIPTION
**Pull request by kpishere**
Here is DMA supported transfers with SPI (and likely other devices).

There is still a bug with the DMA completion.  The test is configured to trigger an interrupt but it is not firing.  So, the busy wait loop is also polling until DMA is completed.

I'm thinking it is still worthy of sharing.  A smaller update can follow with fixing that.  (I did having it working at one point but something has changed .. possibly panic levels or mid to high water marks).

Regardless, all bytes transfer as expected.

### CODE REVIEW

**Comment by kpishere** [comment]
It is also super fast.  I have to slow down the clock to 1/8 speed (33Mhz) for the connected logic analyzer but with the targeted SPI display and it's short wires, it should be able to go up to 66 Mhz.  The bytes are fully packed in the stream with no inter-message delays.  A beautiful thing.

**Comment by anton-bondarev** [comment]
@kpishere Thanks a lot.
It's great that it works! However, I see changes in common parts (SPI subsystem and spi command) it seems that they can break other platforms. Could you please extract them in separate commits? and after that think about how to extend existed SPI API with your suggestions. I'll also think about it. It takes me several days to suggest a fit way.

**Comment by kpishere** [comment]
@anton-bondarev Gave it another look over. The 'add support for DMA transfers' updates only the shared spi.h file.  It adds new properties only.  There is an exception, I'd changed the return type on interrupt handlers -- that was only recently added by me so I'd be expecting not too much dependancy yet?

The more problematic one may be the spi test command though.  Should I make a new command in the raspi target for the dma support?  It could be like that until we settle on a generic API for DMA?  Or, maybe you could suggest a way to make only parts compile for a given target?  Think you'd mentioned a compile-time switch based on target in a prior set of comments.  Which would you prefer to see here?

**Comment by anton-bondarev** [comment]
> @anton-bondarev Gave it another look over. The 'add support for DMA transfers' updates only the shared spi.h file. It adds new properties only. There is an exception, I'd changed the return type on interrupt handlers -- that was only recently added by me so I'd be expecting not too much dependancy yet?

Ops, sorry. I see now. You changed handler type 'irq_event_t' -> 'irq_spi_event_t'. Therefore I've seen changes in spi.h. It's normal, but could you extract it into a separate commit. Besides this, we have to make sure that 'irq_event_t' is not used anywhere else.

**Comment by anton-bondarev** [comment]
@kpishere Hi
I have some suggestions about how to add DMA support to 'spi' command and keep it independent on a specific platform. I think we can achieve this if add set_interrupt_handler routine to SPI API. Also, we should extend DMA API to getting DMA status (you use bcm283x_dma_in_progress() now).

The other changes is good for me. Could you please extract "update spi test command for new dma tests" commit to another branch and  if it is not difficult please split "add support for DMA transfers " commit in two (SPI API add DMA support and bcm spi add dma support)

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by kpishere** [comment]
@anton-bondarev Hah!  Well I've been working on this.  I've been extending DMA to have an abstract API (No file system device, the bare minimum struct of function pointers only).  Then SPI interface can be extended in abstract way to support DMA.  I'm a little slow here as I'll have to make Qemu environment test for STM32 just to make sure the dma_test command works with a simple DMA memory copy still.

I'll make separate branches for the DMA changes, then the SPI changes and their respective command updates.  I was working with your thought that it would be nice to have one spi command for all methods, polling, interrupt, and dma transfer.

Anybody gonna pickup better support for dma on stm32?  I'm just gonna support the bare minimum that is there now. AKA no stm32 dma to peripheral support from me.

Note: once this stuff is working, I can _finally_ work on incorporating the SPI driver for LCD displays!

**Comment by anton-bondarev** [comment]
@kpishere Great!
There are several STM32 in my hand now, so I can try to check and improve your driver for DMA STM32 as need. But unfortunately, I haven't any SPI devices now. However, I think it is not a big problem, because it can be solved if the problem appears in the future. Now we can do a minimal driver.

**Comment by anton-bondarev** [comment]
@kpishere I even think you may use stubs for STM version at this stage.

**Comment by kpishere** [comment]
@anton-bondarev Ok, so I think it is ready for STM32 testing.  I've made another PR from another branch for just the DMA changes (Bcm dma #2483).  Probably want to test/review that one before this one.  this one includes the changes in the other one as the following SPI changes are dependant on that one.  If you want to break it up and test that one separately, definitely do that one first.  If you think it is all good, then can accept this one and reject the other.

There are no functional changes from the last submission, just re-factoring to separate out device specific info for each implementation of DMA and SPI.

**Comment by kpishere** [comment]
@anton-bondarev This PR for the SPI extension has been updated to the new DMA device name for PL330.  PR Ready to be completed and merged?

**Comment by kpishere** [comment]
@anton-bondarev Consolidated the commits into more functional bits after rebasing off of master.

**Comment by anton-bondarev** [comment]
@kpishere Thanks a lot for your efforts. Great job. I've merged the PR now.

**Comment by anton-bondarev** [comment]
@kpishere I have fixed some dependencies in 2485

**Pull request merged**
