### PR TITLE
improve stm32/nucleo_f410rb template

### PR DESCRIPTION
**Pull request by ASASSd**
Improve template for stm32 Nucleo64-F410RB board - expand functionality and optimize compiler flags

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
:shipit:

**Comment by anton-bondarev** [comment]
@ASASSd Thanks a lot. I've merged it
Could you also add 'ticker' command for time checking

**Comment by ASASSd** [comment]
yes, i'll do this
and do we need Coremark? if yes, i'll include it in commands

вс, 1 окт. 2023 г., 15:56 Anton Bondarev ***@***.***>:

**Comment by anton-bondarev** [comment]
> and do we need Coremark? if yes, i'll include it in commands

Yes, sure. It will be great!

**Pull request merged**
