### PR TITLE
Nucleo f030r8

### PR DESCRIPTION
**Pull request by Vadimatorik**
I have added port for nucleo-f030r8. It contains driver for gpio and usart (with internal gpio init for initialising gpio in arch method). Without HAL. Only my code.

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@Vadimatorik Thanks a lot. Looks good.

Could you please split your PR for atomic commits. I see some clear of them: uart driver, gpio driver, nucleo-f030r8 support part, nucleo-f030r8 template. Maybe something else.

To do this. you have to update your repo under embox/master 
```
git fetch upstream
git rebase upstream/master
```
and force push your branch
```
git push origin +<your_branch_name>
```
And modify your commits history with 
```
git rebase -i upstream/master
```
after the command, you have to see your commits log and you would be able to modify it

**Comment by Vadimatorik** [comment]
Okay. I have done it.

**Comment by Vadimatorik** [comment]
Oh... I haven't reverted commits name. I need to one minute.

**Comment by Vadimatorik** [comment]
Okay. Now it is good.

**Comment by anton-bondarev** [comment]
@Vadimatorik Cool. 

There are some minor troubles in code for example `asm(nop` in arch_init or magic address constants, but for the first time it is great! I've approved it. Than you!

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by Vadimatorik** [comment]
"NOP" was added by me for correct sequence write to registers. I will add comments about it for next version arch_init with multy-values for  RCC. For magic constants a gave references for reference manual and other documents.

**Comment by anton-bondarev** [comment]
> "NOP" was added by me for correct sequence write to registers. I will add comments about it for next version arch_init with multy-values for RCC. For magic constants a gave references for reference manual and other documents.

No problem. It's just advice for the future :) 
I've merged it. Thank you very much!

**Pull request merged**
