### PR TITLE
Add tests for strupr() and strlwr()

### LINKED ISSUE #1849: Add test for strupr() & strlwr()
Implement tests for standard routines strupr() & strlwr()

### PR DESCRIPTION
**Pull request by FrackeR011**
Fixes #1849.
Added test cases for strlwr() and strupr() functions.

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@FrackeR011 
Thanks. It's good. But may be you can add some more tests, For example compare different strings or strings with different length?

**Comment by FrackeR011** [comment]
@anton-bondarev I have added more test cases.

**Comment by anton-bondarev** [comment]
@FrackeR011
Thank you. I've approved PR. Please squash the commit and add your tests to x86/test/unit template by a separate commit.

And we are waiting for your email!

**Comment by FrackeR011** [comment]
Done. I am writing the email now.

**Comment by anton-bondarev** [comment]
@FrackeR011 Please, Can you resolve conflicts with embox/master?

**Comment by FrackeR011** [comment]
Should I squash the merge commit or leave it as it is?

**Comment by alexkalmuk** [comment]
@FrackeR011 Yes, you should have only your two commits on the top (so do not merge, but make rebase).

**Comment by FrackeR011** [comment]
@alexkalmuk Done.

**Comment by anton-bondarev** [comment]
@FrackeR011 
Thank you. That's ok now.

**Pull request merged**
