### PR TITLE
modified uart_rx_buff_put() to clear buffer

### LINKED ISSUE #1954: Characters get lost while copying a long (more then 7 symbols) string to the console
To reproduce the problem you can
* run x86/qemu or arm/qemu template
* Copy to clipboard "1234567890"
* Paste to Embox command line

You see "12345678" instead of  "1234567890"

### PR DESCRIPTION
**Pull request by sobhaniiest**
This will fix #1954 
Thanks @anton-bondarev for helping me out!

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@sobhaniiest Thanks
You in the right way. But You could not call uart_rx_action() directly from IRQ context. You must do it through calling lthread_launch(&uart_rx_irq_handler);
Therefore as I described in issue #1954 it's required to expand UART API (struct uart_ops) with enabling/disabling IRQ handlers.

**Comment by sobhaniiest** [comment]
> it's required to expand UART API (struct uart_ops) with enabling/disabling IRQ handlers.

I'm stuck here, I've tried with `irqctrl_disable()` and `irqctrl_enable()` but did not get any result. As I have observed the implementation of `struct uart_ops`, it is different for different architectures. Could you please help to figure out this part. Thanks.

**Comment by anton-bondarev** [comment]
> `irqctrl_enable`

Ooo, You are right  irqctrl_enable(uart->irq_num) can be used for enabling/disabling IRQ. 
Please push your code for this, I try to check why it can not work

**Comment by sobhaniiest** [comment]
This is working but not everytime.

**Comment by anton-bondarev** [comment]
> This is working but not everytime.

@sobhaniiest Thanks
I understood the problem. irqctrl_enable/irqctrl_disable can not be used in this place,  because of irqctrl_enable is called in irq_handlers after treating IRQ handler (we now inside IRQ handler).

I've added uart_irq_en/dis for some serial drivers in #1969. when it's merged you can use in your PR
 
```
static int uart_rx_action(struct lthread *self) {
	struct uart_rx rx;

	while (!uart_rx_buff_get(&rx)) {
		struct uart *dev = rx.uart;

		tty_rx_locked(dev->tty, rx.data, 0);
		dev->uart_ops->uart_irq_en(dev, &dev->params);
	}

	return 0;
}
```
and
```
static int uart_rx_buff_put(unsigned int irq_nr, struct uart *dev) {
	struct uart_rx *rx;

	if (dev->tty) {
		while (uart_hasrx(dev)) {
			irq_lock();
			{
				rx = pool_alloc(&uart_rx_buff);
				if (!rx) {
					dev->uart_ops->uart_irq_dis(dev, &dev->params);
					lthread_launch(&uart_rx_irq_handler);
					irq_unlock();
					return -1;
				}

				rx->uart = dev;
				rx->data = uart_getc(dev);
				dlist_add_prev(dlist_head_init(&rx->lnk), &uart_rx_list);
			}
			irq_unlock();
		}
		lthread_launch(&uart_rx_irq_handler);
	}

	return 0;
}
```

**Pull request closed without merging**
