### PR TITLE
Add atanh() function test file

### LINKED ISSUE #3452: Add tests for atanh() from math.h
Look at [https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c](https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c)

### PR DESCRIPTION
**Pull request by LinkolnR**
Closes #3452

### CODE REVIEW

**Comment by anton-bondarev** [comment]
Hi @LinkolnR
Thanks for the PR. The code looks OK but I don't see how you checked it.
Have you run this test suit? it's necessary before your changes will be merged!

**Comment by LinkolnR** [comment]
Hi @anton-bondarev!
Oops, I forgot to add the tests in GitHub Action. I tried adding them in the x86 tests, but it gave an error in the risc64/test/units files. Is there any other file I need to change?

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
> Hi @anton-bondarev! Oops, I forgot to add the tests in GitHub Action. I tried adding them in the x86 tests, but it gave an error in the risc64/test/units files. Is there any other file I need to change?

Hi @LinkolnR No it's enough now. Thanks a lot. The main missed change was module description (in Mybuild file).
I mean you must run your code locally first of all And yes it's a good way to run your code  in GitHub Action!

I've approved the PR. Could you prepare to merge. I mean you should rebase your branch under upstream/master 
[https://github.com/embox/embox/wiki/Contributing%3A-Git-workflow](https://github.com/embox/embox/wiki/Contributing%3A-Git-workflow )

**Comment by anton-bondarev** [comment]
@LinkolnR I mean you should do following

checkout your branch (issue-3452)
`git checkout issue-3452`
Add embox as upstream if it miss ( `git remote  -v`)
`git remote add upstream https://github.com/embox/embox.git`
Fetch upstream
`git fetch upstream`
Synchronize (rebase under upstream/master)
`git rebase upstream/master`
Force push to your branch ([issue-3452](https://github.com/LinkolnR/embox/tree/issue-3452) )
`git push origin +issue-3452`

**Comment by anton-bondarev** [comment]
@LinkolnR Sorry, I see the only one commit (and a changed file) again :(

**Comment by LinkolnR** [comment]
Oppps, sorry i will fix this

**Comment by anton-bondarev** [comment]
@LinkolnR Ohh, I see several strange changes (Merge commit for example) and [https://github.com/embox/embox/pull/3460/commits/041b110843c2fba25994112c3938aae3a44b9ef5](https://github.com/embox/embox/pull/3460/commits/041b110843c2fba25994112c3938aae3a44b9ef5) this one.

Could you please clean the commits?

You can create a new branch and interactive rebase in it (git rebase -i upstream/master)

**Comment by LinkolnR** [comment]
Sorry for causing all that confusion and for the delay. I'm a bit short on time, but does it look good now?

**Comment by anton-bondarev** [comment]
> Sorry for causing all that confusion and for the delay

No problem. :)

> does it look good now?
almost :)

Let's try to remove the last commit (@LinkolnR
[Update mods.conf](https://github.com/embox/embox/pull/3460/commits/6f99028f4fcd0d08ded060068dea20aadd6c1199) )

```
git fetch upstream
git rebase -i upstream/master
```
remove the last commit (You will see commits list in your editor. Just remove the last line (with the commit))

and force push again
`git push origin +issue-3452`

Sorry for the requests

**Comment by LinkolnR** [comment]
Is that it?

**Pull request merged**
