### PR TITLE
Bootpc-dhcp

### PR DESCRIPTION
**Pull request by anton-bondarev**
Fix 'bootpc' requesting address from 'busybox' 'udhcpd' and refactoring bootpc & bootp lib

### CODE REVIEW

**Comment by alexkalmuk** [comment]
LGTM

**Comment by AntonKozlov** [comment]
Had no time to check yet =( Hope to check in couple days

**Comment by AntonKozlov** [comment]
busybox-1.23.2 with config [udhcpd.txt](https://github.com/embox/embox/files/90976/udhcpd.txt)
```
anton@zephyr:~/downloads/busybox-1.23.2$ sudo ./busybox udhcpd -f udhcpd.txt -vvv
Attaching option 01 to list
Attaching option 33 to list
udhcpd (v1.23.2) started
udhcpd: can't open '/var/lib/misc/udhcpd.leases': No such file or directory
IP 10.0.2.10
Adapter index 11
MAC aa:bb:cc:dd:ee:ff
Opening listen socket on *:67 tap0
Received a packet
 hlen 6 xid 0 ciaddr 0 yiaddr 0 siaddr 0 giaddr 0
 chaddr aabbccddee0200000000000000000000
Option found: 0x35 01
Option 0x36 not found
Option 0x32 not found
Received DISCOVER
Adding option: 0x35 02
Adding option: 0x36 0a00020a
No arp reply received for this address
Option 0x0c not found
Option 0x33 not found
Adding option: 0x33 000d2f00
Adding option: 0x01 ffffff00
Sending OFFER of 10.0.2.128
Broadcasting packet to client
 hlen 6 xid 0 ciaddr 0 yiaddr 8002000a siaddr 0 giaddr 0
 chaddr aabbccddee0200000000000000000000
```

embox with x86/bootpc (virtio used). Seems to obtain ip
```
anton@zephyr:~/embox/embox$ export AUTOQEMU_KVM_ARG=""
anton@zephyr:~/embox/embox$ ./scripts/qemu/auto_qemu 
AUTOQEMU_ARCH: x86 (guessed)
AUTOQEMU_MEM: 256 (guessed)
AUTOQEMU_NICS: virtio (guessed)
AUTOQEMU_NICS_CONFIG: (got)
AUTOQEMU_KVM_ARG: (got)
AUTOQEMU_LOAD_ARG: -kernel ./build/base/bin/embox (guessed)
AUTOQEMU_NOGRAPHIC_ARG: -nographic (guessed)
AUTOQEMU_MACHINE: (guessed)
sudo qemu-system-i386 -kernel ./build/base/bin/embox -m 256 -net nic,vlan=0,model=virtio,macaddr=AA:BB:CC:DD:EE:02 -net tap,script=./scripts/qemu/start_script,downscript=./scripts/qemu/stop_script,vlan=0 -nographic
ioctl(TUNSETIFF): Device or resource busy
Enable IP Forwarding for wlp3s0
net.ipv4.ip_forward = 1

Embox kernel start
...
> bootpc eth0 
root@embox:/#ifconfig
lo      Link encap:Local Loopback
        inet addr:127.0.0.1  Mask:255.0.0.0
        inet6 addr: ::/??  Scope:Host
        UP LOOPBACK RUNNING  MTU:16436  Metric:0
        RX packets:64 errors:0 dropped:0 overruns:0 frame:0
        TX packets:128 errors:0 dropped:0 overruns:0 carrier:0
        collisions:0
        RX bytes:3391 (0 MiB)  TX bytes:6782 (0 MiB)

eth0    Link encap:Ethernet  HWaddr aa:bb:cc:dd:ee:02
        inet addr:10.0.2.128  Bcast:10.0.2.255  Mask:255.255.255.0
        inet6 addr: ::/??  Scope:Host
        UP BROADCAST RUNNING MULTICAST  MTU:1514  Metric:0
        RX packets:0 errors:0 dropped:0 overruns:0 frame:0
        TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
        collisions:0
        RX bytes:0 (0 MiB)  TX bytes:384 (0 MiB)
        Interrupt:11 Base address:0x0000c000
root@embox:/#route
Destination     Gateway         Genmask         Flags  Iface
127.0.0.0       *               255.0.0.0       U         lo
default         *               255.255.255.0   U       eth0

```

But not pings from host
```
anton@zephyr:~$ ping 10.0.2.128
PING 10.0.2.128 (10.0.2.128) 56(84) bytes of data.
^C
--- 10.0.2.128 ping statistics ---
22 packets transmitted, 0 received, 100% packet loss, time 21007ms
```

Tcpdump log

```
23:35:43.724751 IP 10.0.2.10 > 10.0.2.128: ICMP echo request, id 9322, seq 1, length 64
23:35:44.731735 IP 10.0.2.10 > 10.0.2.128: ICMP echo request, id 9322, seq 2, length 64
23:35:45.731663 IP 10.0.2.10 > 10.0.2.128: ICMP echo request, id 9322, seq 3, length 64
23:35:46.731665 IP 10.0.2.10 > 10.0.2.128: ICMP echo request, id 9322, seq 4, length 64
23:35:47.731665 IP 10.0.2.10 > 10.0.2.128: ICMP echo request, id 9322, seq 5, length 64
23:35:48.731665 IP 10.0.2.10 > 10.0.2.128: ICMP echo request, id 9322, seq 6, length 64
23:35:49.731665 IP 10.0.2.10 > 10.0.2.128: ICMP echo request, id 9322, seq 7, length 64
```

Not pings from embox too
```
root@embox:/#ping 10.0.2.10
PING 10.0.2.10 (10.0.2.10) 64 bytes of data
ping: sendto() failure: Network is unreachable
--- 10.0.2.10 ping statistics ---
4 packets transmitted, 0 received, +0 errors, 100% packet loss, time 1ms
ping: Command returned with code -351: Network is unreachable
```

I can confirm, that `rt_fib_get_best` gives NULL route for that request. Check on line 247 is not satisfied
```
(gdb) 
247                     if (((dst & rt_info->entry.rt_mask) == rt_info->entry.rt_dst)
(gdb) list
242             best_rte = NULL;
243             best_mask_len = -1;
244             dlist_foreach_entry(rt_info, &rt_entry_info_list, lnk) {
245                     mask_len = ~rt_info->entry.rt_mask
246                             ? bit_clz(ntohl(~rt_info->entry.rt_mask)) + 1 : 32;
247                     if (((dst & rt_info->entry.rt_mask) == rt_info->entry.rt_dst)
248                                     && (out_dev == NULL || out_dev == rt_info->entry.dev)
249                                     && (mask_len > best_mask_len)) {
250                             best_rte = &rt_info->entry;
251                             best_mask_len = mask_len;
(gdb) p/x dst
$15 = 0xa02000a
(gdb) p/x ((dst & rt_info->entry.rt_mask))
$16 = 0x2000a
(gdb) p/x rt_info->entry.rt_dst
$17 = 0x0
```

Seems like 
1. Route should contain subnet mask, not `default`. May be my udhcpd config is not correct? Or bootpc mistakes when sets route?
2. Even with `default` destination, route should be taken for this request. Is `0.0.0.0/255.255.255.0` route is correct?

**Comment by anton-bondarev** [comment]
Thanks for checking!
You have correct config for dhcp server, but if you set 'opt router	10.0.2.10' you'll see correct ping from both side.
root@embox:/#route
Destination     Gateway         Genmask         Flags  Iface
127.0.0.0       *               255.0.0.0       U         lo
10.0.2.0        *               255.255.255.0   U       eth0
default         10.0.2.10       0.0.0.0         UG      eth0

This is another problem (not bootpc) in our IP stack!

**Comment by AntonKozlov** [comment]
After the changes I have pings going with and without router option. Thanks, LGTM!

**Pull request merged**
