### PR TITLE
Add tests for exp2() from math.h

### PR DESCRIPTION
**Pull request by LidiaDomingos**
Hi!! I made the tests for exp2() as requested in issue #3453 

Let me know if it needs any change, I did it based on previous accepted PRs!

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
@LidiaDomingos Thank you.

I've approved the PR. Could you prepare to merge (rebase it under embox/master)?

[https://github.com/embox/embox/wiki/Contributing%3A-Git-workflow](https://github.com/embox/embox/wiki/Contributing%3A-Git-workflow)

**Comment by LidiaDomingos** [comment]
Hi!! Did what you asked! Is everything okay? Let me know if it isn't

**Comment by anton-bondarev** [comment]
> Hi!! Did what you asked! Is everything okay? Let me know if it isn't

Not yet, I mean you should do following in a console

checkout your branch (add-test-exp2)
    `git checkout add-test-exp2`
Add embox as upstream if it miss ( git remote  -v)
    `git remote add upstream https://github.com/embox/embox.git`
Fetch upstream
   `git fetch upstream`
Synchronize (rebase under upstream/master)
  `git rebase upstream/master`
Force push to your branch ([add-test-exp2](https://github.com/LidiaDomingos/embox/tree/add-test-exp2) )
  `git push origin +add-test-exp2`

In this case you will see only your commits (without merge commits)

**Comment by anton-bondarev** [comment]
Hi @LidiaDomingos thanks a lot.
It's okay now
We've merged your pr

**Pull request merged**
