### PR TITLE
Clear 'duktape' port

### LINKED ISSUE #2822: Clean 'duktape' port
Move fib.js to a apropriate templates where it needs
```
	@InitFS
	source "fib.js"
```

### PR DESCRIPTION
**Pull request by DmitryPilyuk**
Fix #2822

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
@DmitryPilyuk Thanks. Ive aproved it. Could you please rebase your branch under embox/master?

**Comment by DmitryPilyuk** [comment]
@anton-bondarev, Ok, the branch has been rebased.

**Comment by anton-bondarev** [comment]
@DmitryPilyuk Thanks. I've merged it

**Pull request merged**
