### PR TITLE
drivers: Add SiFive CLINT support and refactor riscv_clk module

### PR DESCRIPTION
**Pull request by SurajSonawane2415**
This PR adds support for the SiFive Core Local Interruptor (CLINT) to enable multi-hart architecture. It also refactors `riscv_clk` module functions by replacing direct register operations with function calls:

- Replaced `REG64_STORE(MTIMECMP, REG64_LOAD(MTIME) + COUNT_OFFSET);` with `clint_set_mtimecmp(clint_get_mtime() + COUNT_OFFSET);`.

These changes were tested using the `riscv/qemu` template.

Documentation reference: [SiFive U54-MC Core Complex Manual](https://static.dev.sifive.com/U54-MC-RVCoreIP.pdf)

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
@SurajSonawane2415 Thanks a lot!

**Comment by SurajSonawane2415** [comment]
@anton-bondarev Thanks for merging this PR!

**Comment by sycamoremoon** [comment]
Sorry, could you explain a little bit why we should distinguish `SIFIVE_CLINT` situation for me? I try to use `CLINT` for CPU IPI communication but felt confused for the  `SIFIVE_CLINT` macro?
I could not seem to find a description of it from [RISCV_CLINT document](https://github.com/riscv/riscv-aclint/blob/main/riscv-aclint.adoc). By this way, where should I enable the `SIFIVE_CLINT` macro?

**Comment by SurajSonawane2415** [comment]
SIFIVE_CLINT supports multi hart architecture. But I replaced SIFIVE_CLINT with SMP #3397 for better understanding, as per discussion with you. Thank you for your suggestion.

**Pull request merged**
