### PR TITLE
add riscv64

### PR DESCRIPTION
**Pull request by sk2sat**
Add minimal arch/riscv64 & riscv64/qemu template.

It can boot on qemu-system-riscv64(but stuck at initializing clock driver).

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@sk2sat Great!
Thanks a lot! It's enough for starting!

**Comment by sk2sat** [comment]
@anton-bondarev thanks! So I would like to work on timer problem.

**Comment by anton-bondarev** [comment]
> @anton-bondarev thanks! So I would like to work on timer problem.

@sk2sat Would you like to work on timer in this PR? I think that this PR can be merged in the current state and you can work in a new PR

**Comment by sk2sat** [comment]
> @sk2sat Would you like to work on timer in this PR? I think that this PR can be merged in the current state and you can work in a new PR

@anton-bondarev 
I think so too. The purpose of this PR is only to add a riscv64 target and run it on QEMU.

**Comment by anton-bondarev** [comment]
@sk2sat Thanks. I've  merged it

**Comment by anton-bondarev** [comment]
Close #2014

**Pull request merged**
