### PR TITLE
Add coremark cmd

### PR DESCRIPTION
**Pull request by ASASSd**
Added Coremark benchmark port with static iterations number

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
@ASASSd Thanks. I've aproved this PR.
However it's better to use third-party for such project (download the based project sourses, patched it and build)

Could you also prepare to merge this PR.
You have to rebase your branch
I mean
1. Set embox main repo as upsteram
[https://github.com/embox/embox/wiki/Contributing%3A-Git-workflow#clone-the-repository](https://github.com/embox/embox/wiki/Contributing%3A-Git-workflow#clone-the-repository)
```git remote -v
...
git remote add upstream https://github.com/embox/embox.git
git remote -v
# origin    https://github.com/YOUR-USERNAME/embox.git (fetch)
# origin    https://github.com/YOUR-USERNAME/embox.git (push)
# upstream  https://github.com/embox/embox.git (fetch)
# upstream  https://github.com/embox/embox.git (push)
```
2. fetch upstream
```
git fetch upstream
```
3. Rebase under upstream/master
```
git rebase upstream/master
```

You can also use interactive mode during rebasing
`git rebase -i upstream/master`

**Comment by ASASSd** [comment]
rebased successfully. also moved coremark to third-party

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by ASASSd** [comment]
rebased branch one more time. i've done it from other PC, and there old variant (with coremark in src/cmds/testing) was pushed to my remote "origin". i rebased one more time from correct PC and then manually removed coremark dir from src/cmds/testing

**Pull request merged**
