### PR TITLE
Add httpd with pthread

### PR DESCRIPTION
**Pull request by Nastasya-Vinogradik**

### CODE REVIEW

**Comment by abusalimov** [comment]
Thank you!

This looks very alike the original `httpd.c` reorganized in #735 recently. Shouldn't this be merged with non-pthread version, making the threading feature optional? @AntonKozlov, WDYT?

Also, please consider running `git diff --check HEAD^`, fixing highlighted whitespace errors and amending the commit.

**Comment by AntonKozlov** [comment]
IMO, request could be merged as-is, and pthread support implemented as option later

**Comment by abusalimov** [comment]
OK, it's on your conscience, although it's harder to review the whole file instead of the diff.

Anyway, I'll wait until whitespace issues are resolved, and someone reviews the actual code.

**Comment by anton-bondarev** [comment]
Ok, I'm agree that this request can be merged but in the future you should merge both version of httpd and use Mybuuild options for switching them

**Comment by AntonKozlov** [comment]
@Nastasya-Vinogradik Httpd was heavly modified in upstream, this pull request can't be merged. I've started from this changes and modifed reworked httpd-pthread as in upstream. Please check #791

**Comment by AntonKozlov** [comment]
@Nastasya-Vinogradik Feel free to reopen this PR/start another one if #791 has flaws

**Pull request closed without merging**
