### PR TITLE
Docker build

### PR DESCRIPTION
**Pull request by AntonKozlov**

### CODE REVIEW

**Comment by anton-bondarev** [comment]
Is this realy required to modify '.cproject' file?

**Comment by AntonKozlov** [comment]
Yes, since new build target introduced.
https://github.com/embox/embox/pull/939/commits/7ff24c94d78ff8c7543f6c1ab1caab8bdf3869c1

should make it clear

**Comment by AntonKozlov** [comment]
Hi! How the review going?

**Comment by anton-bondarev** [comment]
Hi! 
Sorry. we were not still check it on Windows.
It looks good, You can merge it now or wait before we try it on Windows

**Comment by anton-bondarev** [comment]
LGTM
I checked it on windows but without eclipse

**Pull request merged**
