### PR TITLE
Codestyle check based on uncrustify

### PR DESCRIPTION
**Pull request by AntonKozlov**
* Uncommited changes check
* Commit range check
* Pull-request check (via travis)

Rebase of #1072

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@AntonKozlov How can I check it?

**Comment by AntonKozlov** [comment]
@anton-bondarev it's actually a question if it will disrupt workflow of team. 
Travis run of this PR (https://travis-ci.org/embox/embox/builds/250302340) demonstrates new job UNCRUSTIFY. The job could fail (https://travis-ci.org/embox/embox/builds/250088482) if there is errors in codestyle.
Suggested workflow is: if job failed, not apply codestyle corrections from job output blindly, but check are they meaningful first and probably make corrections in different way. 
For example, if line width of 80 exceeded, the job will suggest to reline code, but sometime in ugly way. The developer should reline manually to not exceed width, but in beautiful way.
`scripts/codestyle/run_uncrustify.sh` could be run to check uncommitted changes before commit (require `uncrustify` tool)

**Comment by anton-bondarev** [comment]
@AntonKozlov Let's try/ But I still havn't understood how will be presented error message if codestile is corrupted
Now in broken check I see following

```
0.21s$ ./travis_uncrustify.sh

/Users/travis/build/embox/embox/scripts/codestyle

./travis_uncrustify.sh: line 2: 1072: command not found

src/

The command "./travis_uncrustify.sh" exited with 1.
cache.2

store build cache

0.01s

2.95schanges detected, packing new archive

uploading archive

Done. Your build exited with 1.

/Users/travis/.travis/job_stages: line 156: shell_session_update: command not found
```

**Comment by AntonKozlov** [comment]
Thanks for noticing that, I missed some recent changes in the parent PR. Please, don't merge this for a while

**Comment by AntonKozlov** [comment]
Example of bad code-style, caught by check https://travis-ci.org/embox/embox/builds/251690082

**Comment by AntonKozlov** [comment]
Remaining conserns fixed, the check able to catch issues in code style. Feel free to open issues or contact me in case of issues with checks itself.
Since there is an approval on approach, I'm merging this.
Thanks to everyone involved!

**Pull request merged**
