### PR TITLE
Update thread command

### PR DESCRIPTION
**Pull request by ameetsaahu**
Updated the thread command to show Task name and stack size.

### CODE REVIEW

**Comment by alexkalmuk** [comment]
Looks great! But there is no need to re-open PR, you can push fixes in the current one :)

**Comment by alexkalmuk** [comment]
@ameetsaahu Please squash your commits into a single one.

**Comment by ameetsaahu** [comment]
Hey, can you please help me about how to squash them into a single one.

**Comment by alexkalmuk** [comment]
> Hey, can you please help me about how to squash them into a single one.

https://github.com/embox/embox/wiki/Contributing%3A-Git-cheatsheet#squash-commits-into-a-single-one

**Comment by ameetsaahu** [comment]
amit@PC:~/embox$ git rebase --interactive 
Successfully rebased and updated refs/heads/master.
amit@PC:~/embox$ 


I did this but still its not done.

**Comment by ameetsaahu** [comment]
IS it fine if remove these two pull requests and make another pull request with all the commits.

**Comment by alexkalmuk** [comment]
> amit@PC:~/embox$ git rebase --interactive Successfully rebased and updated refs/heads/master. amit@PC:~/embox$
> 
> I did this but still its not done.


Did you also do the following what described by the link I provided?

pick   cf5e2f4 net: Add support for ...
squash b54da44 (oops) Missing header file
squash acd54ef (minor) Fix code style
squash fe29a8c sorry, remove trailing whitespaces

**Comment by ameetsaahu** [comment]
Yes, I tried this one also now.
I am a newbie to git and it's going complicated.
I think it will be better to remove these PRs and make a new one.

**Comment by alexkalmuk** [comment]
> Yes, I tried this one also now.
> I am a newbie to git and it's going complicated.
> I think it will be better to remove these PRs and make a new one.

Ok then.

**Comment by alexkalmuk** [comment]
I see you created https://github.com/embox/embox/pull/1803

Close the current one?

**Comment by alexkalmuk** [comment]
OK, I close this one then

**Pull request closed without merging**
