### PR TITLE
Add error check in printf

### LINKED ISSUE #1722: printf must check return value from printchar_handler
printf() must return error code if printchar_handler() failed

### PR DESCRIPTION
**Pull request by sk2sat**
Fix #1722

### CODE REVIEW

**Comment by Deryugin** [comment]
Thank you for pull request! It looks fine, but there are some minor [code-style](https://github.com/embox/embox/wiki/Code-Style) issues.
* Add a single space symbol after `if`, i.e. replace `if(...)` with `if (...)`
* Add braces for single-state `if` construction (I know, there were no braces for `while()` loops too, but that's a bad code example), so please replace `if (...) foo();` with
```
if (...) {
    foo();
}
```

**Comment by sk2sat** [comment]
@Deryugin thanks for feedback! I will check coding style before submit PR.

**Comment by Deryugin** [comment]
Now it's good!

Please, squash your fixup commits and I'll merge it to master.

P.S. Initial changes in a57189a3fd24fcf9cad623862f8134785dcd895a were actually correct and we have bug in `printf_test`; but that's different issue.

**Comment by sk2sat** [comment]
Done squash commits and I understand the issue.

**Pull request merged**
