### PR TITLE
ext2fuse

### PR DESCRIPTION
**Pull request by Deryugin**
ext2fuse support for new VFS

### CODE REVIEW

**Comment by anton-bondarev** [comment]
LGTM

**Comment by abusalimov** [comment]
WTF is the `patch.txt` file inside the root directory?

**Comment by abusalimov** [comment]
> WTF is the `patch.txt` file inside the root directory?

ping @embox/devs

**Comment by anton-bondarev** [comment]
@abusalimov Thanks for your notice.
Please, next time you should create an issue or a PR for your problem. It's more comfortable place to discuss or resolve one.

**Pull request merged**
