### PR TITLE
1840-memccpy-implementation created

### LINKED ISSUE #1840: Implement memccpy()
`memccpy()` is a part of POSIX standard.

For more details refer to POSIX specification: https://pubs.opengroup.org/onlinepubs/9699919799/

 Also implement some tests as well to make sure it works correctly.

### PR DESCRIPTION
**Pull request by tech-gian**
closes #1840 
That's my try for pull requesting memccpy() implementation. Please let me know, what mistakes did I did and how to corret myself.
P.S. I am not sure if I linked this PR with issue #1840 , assigned to me.

### CODE REVIEW

**Comment by Deryugin** [comment]
I like your tests, it's good that you test both stack and heap memory. Also I think it's a good idea to test not only the fact that prefix of the string was successfully copied, but also check that the rest of destination memory was not corrupted.

I see you have implemented `embox_memcpy()` function to be compiled on host system, but we need to have it as part of Embox.

You don't need to add another test framework (acutest), we have it already; function name should be `memccpy()`, not `embox_memccpy()`; that will allow to run external application which need this function.

Take a look at tests in `src/test` directory.
`memccpy()` function probably should be placed in ` src/compat/libc/string/` directory.

Follow steps from (https://github.com/embox/embox/wiki/Quick-Start) to build Embox.

P.S. Make sure that your code complies with our code style https://github.com/embox/embox/wiki/Code-Style

**Comment by tech-gian** [comment]
So I must correct the "issues" that you mentioned, complie my code with embox's codestyle and place the files into this directory src/compat/libc/string/ ? And then, to pull request again, so you can check that everything works fine? Thank you for your comments and guidance!

**Comment by anton-bondarev** [comment]
> src/compat/libc/string/

Yes, you should just create small function in src/compat/libc/string/

You can create a new PR or revert changes in it.

**Comment by Deryugin** [comment]
@tech-gian 

> So I must correct the "issues" that you mentioned, complie my code with embox's codestyle

Correct

> place the files into this directory src/compat/libc/string/ ?

That's not enough, you should make sure that this module is compiled as a part of Embox. To do so you also need to describe your module in build file, then add this module some config (e.g. x86/test/units) and make sure that your tests are running when you run Embox in the emulator.

**Comment by tech-gian** [comment]
Ok. I think i got it. I will do this and PR again. Thank you!

**Comment by tech-gian** [comment]
I am really sorry that I bother you with probably "beginner's" questions. I have corrected memccpy.c and added it to src/compat/libc/string. I also have corrected memccpy_test.c based on test.h and added it to src/tests/posix. I also have installed my Embox emulator but I don't understand how should I test it. I mean, do I have to change some Mybuild file? If yes, what? Or should I get it in cmds, just to see that it works right (like hello_world from "Getting Started" guide) and live these 2 files there after this?
I apologize again for that misunderstanding, but I am really confused and I think that I should understand exactly what happens, because that is basics.
P.S. I make all these changes to my fork, into a new branch, from which I am going to PR.

**Comment by anton-bondarev** [comment]
The wrong way now it tries to revolve in #1894

**Pull request closed without merging**
