### PR TITLE
Add nucleo f429zi template

### PR DESCRIPTION
**Pull request by anton-bondarev**

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@ThePiGrepper Could you please check this PR on stm32f4-discovery board?

**Comment by ThePiGrepper** [comment]
> @ThePiGrepper Could you please check this PR on stm32f4-discovery board?

ok, already tested the default config and it boots alright, passing the default tests.

PD: I do have a minor gripe though. do we really need to register the node as 'STM32 SPI'? can't it be a single word(maybe separated with [_-] chars) and lowercase? like stm32_spi or stm32spi ?

**Comment by anton-bondarev** [comment]
> > @ThePiGrepper Could you please check this PR on stm32f4-discovery board?
> 
> ok, already tested the default config and it boots alright, passing the default tests.
> 
> PD: I do have a minor gripe though. do we really need to register the node as 'STM32 SPI'? can't it be a single word(maybe separated with [_-] chars) and lowercase? like stm32_spi or stm32spi ?

@ThePiGrepper Thanks a lot!

It's a code style rule. We use upper-case in macro naming for easy to diff from routines and variables

**Comment by ThePiGrepper** [comment]
> > > @ThePiGrepper Could you please check this PR on stm32f4-discovery board?
> > 
> > 
> > ok, already tested the default config and it boots alright, passing the default tests.
> > PD: I do have a minor gripe though. do we really need to register the node as 'STM32 SPI'? can't it be a single word(maybe separated with [_-] chars) and lowercase? like stm32_spi or stm32spi ?
> 
> @ThePiGrepper Thanks a lot!
> 
> It's a code style rule. We use upper-case in macro naming for easy to diff from routines and variables

no problem. :-)
I was talking about the device name though(/dev/STM32 SPI). I understand why a macro should be uppercase. could it be at least not space-separated?

**Comment by anton-bondarev** [comment]
> > > > @ThePiGrepper Could you please check this PR on stm32f4-discovery board?
> > > 
> > > 
> > > ok, already tested the default config and it boots alright, passing the default tests.
> > > PD: I do have a minor gripe though. do we really need to register the node as 'STM32 SPI'? can't it be a single word(maybe separated with [_-] chars) and lowercase? like stm32_spi or stm32spi ?
> > 
> > 
> > @ThePiGrepper Thanks a lot!
> > It's a code style rule. We use upper-case in macro naming for easy to diff from routines and variables
> 
> no problem. :-)
> I was talking about the device name though(/dev/STM32 SPI). I understand why a macro should be uppercase. could it be at least not space-separated?

Ops, do you mean than 'ls /dev' shows "/dev/STM32 SPI" with spaces? Of course, it's not a very good file name. :)
I thought that the name looks like "stm32_spi_1". Thanks a lot!

**Comment by anton-bondarev** [comment]
@ThePiGrepper Thanks a lot!
I've fixed device names for spi controllers, now it does not contain spaces.

**Pull request merged**
