### PR TITLE
Implemented unit tests for strcmp() and strncmp()

### LINKED ISSUE #1853: Add unit tests for strcmp() & strncmp()
Implement some test cases for strcmp() & strncmp()

### PR DESCRIPTION
**Pull request by 287mdsahil**
fixes #1853

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@287mdsahil Thanks
Add also your test to x86/test/unit template by a separate commit, please

**Comment by 287mdsahil** [comment]
Okay, on it.

**Comment by 287mdsahil** [comment]
Please check if its correct.

**Comment by anton-bondarev** [comment]
Yes, it's alright

**Pull request merged**
