### PR TITLE
added st_blocks filling in stat()

### PR DESCRIPTION
**Pull request by InfernalKn1ght**
issue #1739 fix

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
@InfernalKn1ght Thanks. T've approved this PR

However it will be great if you add the same feature to dvfs (You can use arm/qemu or modify mods.conf for test

**Comment by InfernalKn1ght** [comment]
@anton-bondarev I've added this feature to dvfs

**Comment by anton-bondarev** [comment]
@InfernalKn1ght Thanks a lot!

Could you also prepare the PR to merge

   Set embox main repo as upsteram
```
git remote add upstream https://github.com/embox/embox.git
```
    fetch upstream
```
git fetch upstream
```
    Rebase under upstream/master
```
git rebase upstream/master
```
force push your branch
```
git push origin +your_branch_name
```

**Comment by anton-bondarev** [comment]
@InfernalKn1ght Thanks/ I've merged it

**Pull request merged**
