### PR TITLE
Remove #include __impl_x(...)

### LINKED ISSUE #517: __BEGIN_DECLS and __END_DECLS rework
__BEGIN_DECLS and __END_DECLS should be moved from command line compiler flags to elsewhere, possibilities are: dedicated include file, total removal resulting in usual #ifdef __cplusplus

### PR DESCRIPTION
**Pull request by anton-bondarev**
Remove __impl_x() macro. Closes #517.

### CODE REVIEW

**Comment by abusalimov** [comment]
(Offtopic) Instead of writing:
> It also fix issue #517 <https://github.com/embox/embox/issues/517>

Use "closes #517" or "fixes #517". This way, once the PR is merged, the
corresponding issue will be closed automatically.

Regards,
Eldar

**Comment by anton-bondarev** [comment]
Eldar, thanks

**Comment by abusalimov** [comment]
`__impl_x` is a nasty thing, but I don't think removing it is so urgent task wotrh leaving certain headers as copy-paste of api and impl files.

I'm against merging this until at least these files are cleaned up:
 - src/include/framework/test/assert.h
 - src/include/framework/test/emit.h
 - src/include/framework/test/self.h

**Comment by anton-bondarev** [comment]
@abusalimov I'm agree some file are terrible now. I'm going to change them in a next iteration.

**Comment by abusalimov** [comment]
LGTM

**Pull request merged**
