### PR TITLE
Move global headers

### PR DESCRIPTION
**Pull request by anton-bondarev**

### CODE REVIEW

**Comment by abusalimov** [comment]
Please-please-please, don't put the branch name in front of each commit message! It is supposed to be a **subsystem** affected by the change.

**Comment by anton-bondarev** [comment]
> don't put the branch name in front of each commit message

Ok. A change it to 'headers:'

**Comment by abusalimov** [comment]
LGTM

**Comment by abusalimov** [comment]
:shipit:

**Pull request merged**
