### PR TITLE
driver: clock: Add driver support for SP804

### LINKED ISSUE #1769: Implementing sp804 driver
sp804 is a timer module which is used in various ARM boards.
Technical reference manual can be found [here](http://infocenter.arm.com/help/topic/com.arm.doc.ddi0271d/DDI0271.pdf).

It's emulated for qemu vexpress machine, which is already supported (`arm/vexpress-a9` template), so it's required to implement a driver for this timer.

```
(qemu) info mtree
    ...
    0000000010011000-0000000010011fff (prio 0, i/o): sp804
    0000000010012000-0000000010012fff (prio 0, i/o): sp804
```

### PR DESCRIPTION
**Pull request by layman-n-ish**
This adds driver support for ARM Dual-Timer Module (SP804)
which is emulated in qemu-vexpress-a9.

This closes #1769.

Signed-off-by: Nishant Malpani <nish.malpani25@gmail.com>

### CODE REVIEW

**Comment by layman-n-ish** [comment]
I tried testing the SP804 driver by replacing `include embox.driver.clock.cortexa9` with `include embox.driver.clock.sp804` before building _embox_ but it gives me the following warning when running the `arm/vexpress-a9` template on qemu while initializing:

```
> unit: initializing embox.driver.clock.sp804: Timer with delta zero, disabling 
```

Is the timer starting before being initialized? I tried enabling the timer after loading the LR register but it still gives me the same warning.

**Comment by layman-n-ish** [comment]
I'll squash all commits at the end, before merging.

**Comment by alexkalmuk** [comment]
@layman-n-ish The code looks good.


> ```
> > unit: initializing embox.driver.clock.sp804: Timer with delta zero, disabling 
> ```
> 
> Is the timer starting before being initialized? I tried enabling the timer after loading the LR register but it still gives me the same warning.

And timer doesn't work?

**Comment by layman-n-ish** [comment]
> And timer doesn't work?

The `scripts/qemu/auto_qemu` script, after disabling SP804 timer, stalls at the line which initializes  `embox.driver.cache.pl310`, as shown in the screenshot below: 

Screenshot from 2020-03-11 15-17-36

**Comment by alexkalmuk** [comment]
And the same happens even when you load value and only after that enable timer?

**Comment by layman-n-ish** [comment]
> And the same happens even when you load value and only after that enable timer?

Affirmative. 

I'll try running the timer in a different mode (other than free-running mode). I'll let you know how it goes.

**Comment by layman-n-ish** [comment]
> I'll try running the timer in a different mode (other than free-running mode). I'll let you know how it goes.

I tried all the three modes provided in the SP804 timer - free running, periodic and one-shot - all of them produce the same aforementioned issue; they disable the SP804 timer and the `scripts/qemu/auto_qemu` script stalls at `embox.driver.cache.pl310`. How do you propose I debug this issue?

**Comment by anton-bondarev** [comment]
> > I'll try running the timer in a different mode (other than free-running mode). I'll let you know how it goes.
> 
> I tried all the three modes provided in the SP804 timer - free running, periodic and one-shot - all of them produce the same aforementioned issue; they disable the SP804 timer and the `scripts/qemu/auto_qemu` script stalls at `embox.driver.cache.pl310`. How do you propose I debug this issue?

@layman-n-ish Hi
First of all you can try set log_level=4 for pl310 module in conf/mods.config

Then you can use gdb and try what's happened in which line the program broke

And you also can use log_debug for printing where are you
```
static int pl310_init(void) {
	REG_STORE(L2X0_CTRL, 0);

	REG_ORIN(L2X0_AUX_CTRL, L2X0_AUX_INSTR_PREFETCH);
	REG_ORIN(L2X0_AUX_CTRL, L2X0_AUX_DATA_PREFETCH);

	REG_STORE(L70_INVAL, 0xFFF);
	REG_STORE(PL310_BASE + 0x730, 0);
	log_debug("Line %d", __LINE__);
	ksleep(50);
	log_debug("Line %d", __LINE__);
	REG_STORE(L2X0_CTRL, 1);
	log_debug("Line %d", __LINE__);
	asm volatile ("mcr p15, 0, %0, c8, c7, 0" : : "r" (0));
	asm volatile ("mcr p15, 0, %0, c8, c6, 0" : : "r" (0));
	asm volatile ("mcr p15, 0, %0, c8, c5, 0" : : "r" (0));
	log_debug("Line %d", __LINE__);
	_reg_dump("");

	return 0;
}
```
You can also use log_error or other logging level routines. You must set log_level for using routines. as described in the first suggestion

**Comment by anton-bondarev** [comment]
@layman-n-ish Also May be there are problems with interrupts or timer handler, for example timer frequency too high or you don't clear interrupt. You can check it if disable the timer. Or try set breakpoint into interrupt handler.

**Comment by layman-n-ish** [comment]
Hi, 

I kind-of messed up by rebasing from upstream/master while I was trying to push a commit. Yes, I can reflog and revert the changes although I find re-opening this with a new PR much easier. Sorry for any inconvenience caused.

**Pull request closed without merging**
