### PR TITLE
Fixed route command.

### PR DESCRIPTION
**Pull request by onewhl**
See issue #1044.

### CODE REVIEW

**Comment by anton-bondarev** [comment]
@onewhl Thanks!
Looks good to me.
Can you rebase your PR up to embox/master?

**Comment by onewhl** [comment]
Done. Check please.

**Comment by anton-bondarev** [comment]
@onewhl Yes, I've seen that you've already rebased it, but your master is 2 commits behind embox:master

> This branch is 2 commits ahead, 2 commits behind embox:master. 

Please rebase it again.

Except this everything is good!

**Comment by anton-bondarev** [comment]
@onewhl Thanks a lot!

**Pull request merged**
