### PR TITLE
TST: Add test for ceil() in libc tests

### LINKED ISSUE #3269: Add tests for ceil() from math.h
Look at https://github.com/embox/embox/blob/master/src/compat/libc/math/tests/sqrt_tests.c

### PR DESCRIPTION
**Pull request by jasonmokk**
Added unit tests for ceil() in `libc/math/tests`. Closes #3269

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
Thanks.
I've approved it.
Could you also add your new test into the x86/test/units template?

**Comment by jasonmokk** [comment]
> Thanks. I've approved it. Could you also add your new test into the x86/test/units template?

Sure I've updated the PR.

**Comment by anton-bondarev** [comment]
> > Thanks. I've approved it. Could you also add your new test into the x86/test/units template?
> 
> Sure, I've updated the PR.

Thanks.
Please prepare to merge (rebase under upstream/master)

**Comment by jasonmokk** [comment]
> > > Thanks. I've approved it. Could you also add your new test into the x86/test/units template?
> > 
> > 
> > Sure, I've updated the PR.
> 
> Thanks. Please prepare to merge (rebase under upstream/master)

Done!

**Comment by anton-bondarev** [comment]
Thanks, I've merged it

**Pull request merged**
