### PR TITLE
RISCV: Implement SiFive PLIC Driver

### PR DESCRIPTION
**Pull request by SurajSonawane2415**
#2079 

This pull request introduces the implementation of the Platform-Level Interrupt Controller (PLIC) driver for the SiFive U54-MC Core. The driver includes functionality for enabling, disabling, setting priority, and handling interrupts for multiple harts (hardware threads). 

[SiFive U54-MC Core Complex Manual v1p0](https://static.dev.sifive.com/U54-MC-RVCoreIP.pdf)

Please review this pull request and suggest required changes. Thank you!

### CODE REVIEW

**Review by anton-bondarev — APPROVED** [review]
LGTM

**Comment by anton-bondarev** [comment]
Thanks a lot
I've approved this PR
Could you please rebase it under upstream/master?

**Comment by SurajSonawane2415** [comment]
@anton-bondarev I have rebased it onto upstream/master.
Thanks for approving this PR.

**Comment by anton-bondarev** [comment]
> I have rebased it onto upstream/master.

@SurajSonawane2415 Thanks. However I still see "Merge branch 'master' " commit.
Please use the following sequence
```
git fetch upstream
git rebase upstream/master
git push origin +master
```
P. S. for the future. Could you use different branch for working (not 'master')

**Comment by SurajSonawane2415** [comment]
@anton-bondarev Thanks you.

> > I have rebased it onto upstream/master.
> 
> @SurajSonawane2415 Thanks. However I still see "Merge branch 'master' " commit. Please use the following sequence
> 
> ```
> git fetch upstream
> git rebase upstream/master
> git push origin +master
> ```
I had followed this sequence. Can you please check it now?
> P. S. for the future. Could you use different branch for working (not 'master')

Yes, sure. I will keep it in mind.

**Comment by SurajSonawane2415** [comment]
> hello, I have a question about that. Why write a separate `sifive_plic` module instead of directly improving the `riscv_plic` module? They seem to be doing the same things. Could you please explain a little bit to me?

Hey @sycamoremoon, that's great question. I didn't think about that. Maybe @anton-bondarev would be the best person to answer your question.

**Pull request merged**
